console.log("World is very small");
console.log("\"git checkout master\" to switch the branch to master again")

console.log ('\"git init .\" for creating the new git repositiry')
console.log(" \"git add <new file name> \" for adding the file to git")
console.log ('\"git status\" for checking the status of git')
console.log(" \"git commit -m \"<new file name>\" \" for commiting the file to git")
console.log ('\"git log\" for checking the history of commits done')
console.log ('\"git log --oneline\" for checking the history of commits done in one line')
console.log ('\"git checkout -b <name of new branch>\" for checking the history of commits done')
console.log ('\"git branch\" to know the status of current branch')
console.log("\"git checkout <name of branch to switch >\" to switch branch")
console.log("\"git config --global alias.fulltree \"log --color --oneline --graph --decorate --all\"\"now only type \"git fulltree\" to see the log in tree format")
console.log ('\"git remote \" to know the remote of current branch')
console.log ('\"git push origin master \" to push the changes to github')